module.exports = {
  content: [
    './resources/views/**/*.blade.php',
    './resources/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#063e9c',
        'secondary-1': '#183447',
        'secondary-2': '#7093be',
        'secondary-3': '#deedfd',
        secondary1: '#183447',
        secondary2: '#7093be',
        secondary3: '#deedfd',
        light: '#fefefe',
        accent: '#ff8a00',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-primary',
    'text-primary',
    'bg-secondary-1',
    'text-secondary-1',
    'bg-secondary-2',
    'text-secondary-2',
    'bg-secondary-3',
    'text-secondary-3',
    'bg-secondary1',
    'text-secondary1',
    'bg-secondary2',
    'text-secondary2',
    'bg-secondary3',
    'text-secondary3',
    'bg-light',
    'text-light',
    'bg-accent',
    'text-accent',
    'hover:bg-secondary-1',
    'hover:bg-secondary-2',
    'hover:bg-secondary-3',
    'hover:bg-secondary1',
    'hover:bg-secondary2',
    'hover:bg-secondary3',
    'hover:text-accent',
    'from-primary',
    'to-accent',
    'from-accent',
    'to-primary',
    'from-secondary-1',
    'to-secondary-1',
    'from-secondary-2',
    'to-secondary-2',
    'border-primary',
    'border-secondary-1',
    'border-secondary-2',
    'border-secondary1',
    'border-secondary2',
    'border-l-4',
    'border-accent',
    'border-secondary-3',
  ],
}
