<?php

return [
    'defaults' => [
        'hero_title' => 'Social Simulation and Big Data Analytics ITB',
        'hero_description' => 'Pusat riset yang menggabungkan simulasi sosial, analitik big data, dan pendekatan kolaboratif untuk mendukung pembelajaran, penelitian, dan pengabdian akademik.',
        'who_description' => 'Pusat riset yang menggabungkan simulasi sosial, analitik big data, dan pendekatan kolaboratif untuk mendukung pembelajaran, penelitian, dan pengabdian akademik.',
        'who_establish' => 'Membangun pusat riset yang terstruktur, terbuka, dan akademik.',
        'who_value' => 'Memberi nilai melalui riset, talenta, dan kolaborasi lintas bidang.',
        'who_overview' => 'Mendorong dampak nyata lewat pendekatan data dan model sosial.',
        'what_intro_title' => 'Program riset dan aktivitas yang terasa hidup dan mudah dipahami',
        'what_intro_description' => 'Struktur ini dibuat lebih editorial, mirip referensi yang Anda kirim: visual besar di satu sisi, lalu penjelasan yang tegas dan ritmis di sisi lainnya.',
        'what_card_1_title' => 'Student engagement',
        'what_card_1_description' => 'Mendorong partisipasi mahasiswa lewat mentoring, kompetisi, dan program talenta yang terstruktur.',
        'what_card_2_title' => 'Research and funding',
        'what_card_2_description' => 'Dukungan komputasi, proposal, dan pendanaan agar riset bisa berjalan lebih serius dan berkelanjutan.',
        'what_card_3_title' => 'Community and events',
        'what_card_3_description' => 'Menghubungkan lab dengan komunitas melalui workshop, bootcamp, diskusi publik, dan event kolaboratif.',
        'resources_title' => 'Sumber daya dan layanan',
        'resources_description' => 'Daftar ini disusun agar mudah Anda perluas dengan tautan, file, atau halaman detail di kemudian hari.',
        'resource_open_learning_title' => 'Open learning',
        'resource_open_learning_description' => 'Tempat untuk menaruh link YouTube atau video pembelajaran terbuka.',
        'resource_open_learning_link' => 'YouTube Link',
        'resource_cosmos_title' => 'COSMOS',
        'resource_cosmos_description' => 'Collaborative open systems for modelling untuk eksperimen dan simulasi kolaboratif.',
        'resource_dataset_title' => 'Data set',
        'resource_dataset_description' => 'Kumpulan dataset yang relevan untuk riset, pembelajaran, dan prototipe analitik.',
        'resource_module_title' => 'Module',
        'resource_module_description' => 'Modul pembelajaran yang bisa dipakai untuk kelas, workshop, dan pendampingan.',
        'resource_workshops_title' => 'Workshops',
        'resource_workshops_description' => 'Agenda pelatihan rutin untuk mahasiswa, dosen, dan mitra industri atau pemerintah.',
        'resource_intern_title' => 'Intern opportunity',
        'resource_intern_description' => 'Peluang magang riset bagi mahasiswa yang ingin terlibat langsung dalam kegiatan lab.',
        'events_title' => 'Agenda kegiatan',
        'events_description' => 'Bagian ini dapat dipakai sebagai daftar acara, kalender sederhana, atau grid event card.',
        'event_1_title' => 'PBL',
        'event_1_description' => 'Project Based Learning untuk penguatan riset mahasiswa.',
        'event_2_title' => 'Workshops',
        'event_2_description' => 'Sesi pelatihan metodologi, tools, dan presentasi.',
        'event_3_title' => 'Bootcamp',
        'event_3_description' => 'Program intensif untuk data, coding, dan modelling.',
        'event_4_title' => 'Data Detective',
        'event_4_description' => 'Kompetisi analisis data berbasis studi kasus.',
        'event_5_title' => 'ECL',
        'event_5_description' => 'Event akademik dan kolaborasi lintas komunitas.',
        'people_title' => 'Struktur tim inti',
        'people_description' => 'Gunakan kartu ini untuk mengisi nama, peran, dan ringkasan fokus tiap anggota tim.',
        'people_1_name' => 'Nama anggota tim',
        'people_1_bio' => 'Isi dengan foto, jabatan, dan bio singkat sesuai kebutuhan situs Anda.',
        'people_2_name' => 'Nama anggota tim',
        'people_2_bio' => 'Isi dengan foto, jabatan, dan bio singkat sesuai kebutuhan situs Anda.',
        'people_3_name' => 'Nama anggota tim',
        'people_3_bio' => 'Isi dengan foto, jabatan, dan bio singkat sesuai kebutuhan situs Anda.',
        'people_4_name' => 'Nama anggota tim',
        'people_4_bio' => 'Isi dengan foto, jabatan, dan bio singkat sesuai kebutuhan situs Anda.',
        'people_5_name' => 'Nama anggota tim',
        'people_5_bio' => 'Isi dengan foto, jabatan, dan bio singkat sesuai kebutuhan situs Anda.',
        'people_6_name' => 'Nama anggota tim',
        'people_6_bio' => 'Isi dengan foto, jabatan, dan bio singkat sesuai kebutuhan situs Anda.',
        'people_7_name' => 'Nama anggota tim',
        'people_7_bio' => 'Isi dengan foto, jabatan, dan bio singkat sesuai kebutuhan situs Anda.',
        'connect_title' => 'Informasi kontak',
        'connect_description' => 'Simpan semua kanal komunikasi utama di sini agar pengunjung bisa menghubungi pusat riset dengan cepat.',
        'contact_email' => 'ssbda@itb.ac.id',
        'contact_linkedin' => 'linkedin.com/company/ssbda-itb',
        'contact_instagram' => '@ssbda.itb',
        'contact_tiktok' => '@ssbda.itb',
        'contact_facebook' => 'facebook.com/ssbda.itb',
        'contact_youtube' => 'youtube.com/@ssbda-itb',
        'contact_phone' => '+62 22 1234 5678',
    ],
    'sections' => [
        [
            'title' => 'Who we are',
            'fields' => [
                ['key' => 'hero_title', 'label' => 'Hero title', 'type' => 'text'],
                ['key' => 'hero_description', 'label' => 'Hero description', 'type' => 'textarea'],
                ['key' => 'who_description', 'label' => 'Who we are description', 'type' => 'textarea'],
                ['key' => 'who_establish', 'label' => 'Establish', 'type' => 'textarea'],
                ['key' => 'who_value', 'label' => 'Value', 'type' => 'textarea'],
                ['key' => 'who_overview', 'label' => 'Overview', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'What we do',
            'fields' => [
                ['key' => 'what_intro_title', 'label' => 'Intro title', 'type' => 'text'],
                ['key' => 'what_intro_description', 'label' => 'Intro description', 'type' => 'textarea'],
                ['key' => 'what_card_1_title', 'label' => 'Card 1 title', 'type' => 'text'],
                ['key' => 'what_card_1_description', 'label' => 'Card 1 description', 'type' => 'textarea'],
                ['key' => 'what_card_2_title', 'label' => 'Card 2 title', 'type' => 'text'],
                ['key' => 'what_card_2_description', 'label' => 'Card 2 description', 'type' => 'textarea'],
                ['key' => 'what_card_3_title', 'label' => 'Card 3 title', 'type' => 'text'],
                ['key' => 'what_card_3_description', 'label' => 'Card 3 description', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'Resources and Services',
            'fields' => [
                ['key' => 'resources_title', 'label' => 'Section title', 'type' => 'text'],
                ['key' => 'resources_description', 'label' => 'Section description', 'type' => 'textarea'],
                ['key' => 'resource_open_learning_title', 'label' => 'Open learning title', 'type' => 'text'],
                ['key' => 'resource_open_learning_description', 'label' => 'Open learning description', 'type' => 'textarea'],
                ['key' => 'resource_open_learning_link', 'label' => 'Open learning link label', 'type' => 'text'],
                ['key' => 'resource_cosmos_title', 'label' => 'COSMOS title', 'type' => 'text'],
                ['key' => 'resource_cosmos_description', 'label' => 'COSMOS description', 'type' => 'textarea'],
                ['key' => 'resource_dataset_title', 'label' => 'Data set title', 'type' => 'text'],
                ['key' => 'resource_dataset_description', 'label' => 'Data set description', 'type' => 'textarea'],
                ['key' => 'resource_module_title', 'label' => 'Module title', 'type' => 'text'],
                ['key' => 'resource_module_description', 'label' => 'Module description', 'type' => 'textarea'],
                ['key' => 'resource_workshops_title', 'label' => 'Workshops title', 'type' => 'text'],
                ['key' => 'resource_workshops_description', 'label' => 'Workshops description', 'type' => 'textarea'],
                ['key' => 'resource_intern_title', 'label' => 'Intern opportunity title', 'type' => 'text'],
                ['key' => 'resource_intern_description', 'label' => 'Intern opportunity description', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'Events',
            'fields' => [
                ['key' => 'events_title', 'label' => 'Section title', 'type' => 'text'],
                ['key' => 'events_description', 'label' => 'Section description', 'type' => 'textarea'],
                ['key' => 'event_1_title', 'label' => 'Event 1 title', 'type' => 'text'],
                ['key' => 'event_1_description', 'label' => 'Event 1 description', 'type' => 'textarea'],
                ['key' => 'event_2_title', 'label' => 'Event 2 title', 'type' => 'text'],
                ['key' => 'event_2_description', 'label' => 'Event 2 description', 'type' => 'textarea'],
                ['key' => 'event_3_title', 'label' => 'Event 3 title', 'type' => 'text'],
                ['key' => 'event_3_description', 'label' => 'Event 3 description', 'type' => 'textarea'],
                ['key' => 'event_4_title', 'label' => 'Event 4 title', 'type' => 'text'],
                ['key' => 'event_4_description', 'label' => 'Event 4 description', 'type' => 'textarea'],
                ['key' => 'event_5_title', 'label' => 'Event 5 title', 'type' => 'text'],
                ['key' => 'event_5_description', 'label' => 'Event 5 description', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'People',
            'fields' => [
                ['key' => 'people_title', 'label' => 'Section title', 'type' => 'text'],
                ['key' => 'people_description', 'label' => 'Section description', 'type' => 'textarea'],
                ['key' => 'people_1_name', 'label' => 'Role 1 name', 'type' => 'text'],
                ['key' => 'people_1_bio', 'label' => 'Role 1 bio', 'type' => 'textarea'],
                ['key' => 'people_2_name', 'label' => 'Role 2 name', 'type' => 'text'],
                ['key' => 'people_2_bio', 'label' => 'Role 2 bio', 'type' => 'textarea'],
                ['key' => 'people_3_name', 'label' => 'Role 3 name', 'type' => 'text'],
                ['key' => 'people_3_bio', 'label' => 'Role 3 bio', 'type' => 'textarea'],
                ['key' => 'people_4_name', 'label' => 'Role 4 name', 'type' => 'text'],
                ['key' => 'people_4_bio', 'label' => 'Role 4 bio', 'type' => 'textarea'],
                ['key' => 'people_5_name', 'label' => 'Role 5 name', 'type' => 'text'],
                ['key' => 'people_5_bio', 'label' => 'Role 5 bio', 'type' => 'textarea'],
                ['key' => 'people_6_name', 'label' => 'Role 6 name', 'type' => 'text'],
                ['key' => 'people_6_bio', 'label' => 'Role 6 bio', 'type' => 'textarea'],
                ['key' => 'people_7_name', 'label' => 'Role 7 name', 'type' => 'text'],
                ['key' => 'people_7_bio', 'label' => 'Role 7 bio', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'Connect',
            'fields' => [
                ['key' => 'connect_title', 'label' => 'Section title', 'type' => 'text'],
                ['key' => 'connect_description', 'label' => 'Section description', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'type' => 'text'],
                ['key' => 'contact_linkedin', 'label' => 'LinkedIn', 'type' => 'text'],
                ['key' => 'contact_instagram', 'label' => 'Instagram', 'type' => 'text'],
                ['key' => 'contact_tiktok', 'label' => 'TikTok', 'type' => 'text'],
                ['key' => 'contact_facebook', 'label' => 'Facebook', 'type' => 'text'],
                ['key' => 'contact_youtube', 'label' => 'YouTube', 'type' => 'text'],
                ['key' => 'contact_phone', 'label' => 'Phone', 'type' => 'text'],
            ],
        ],
    ],
];