<?php

return [
    'defaults' => [
        'hero_title' => 'Social Simulation and Big Data Analytics Laboratory',
        'hero_description' => 'A research lab focused on social simulation, big data analytics, and collaborative methods that support teaching, research, and academic service.',
        'who_description' => 'A research lab focused on social simulation, big data analytics, and collaborative methods that support teaching, research, and academic service.',
        'who_establish' => 'Build a structured, open, and academically grounded research environment.',
        'who_value' => 'Create value through research, talent development, and cross-disciplinary collaboration.',
        'who_overview' => 'Drive real impact through data-informed approaches and social modeling.',
        'brand_guidelines_description' => 'Use the logo consistently, keep the main name compact, and retain the subtitle Social Simulation & Big Data Analytics Laboratory beneath the visual mark.',
        'what_intro_title' => 'Research programs and activities presented with a clear editorial rhythm',
        'what_intro_description' => 'This layout keeps the structure bold and easy to scan: a strong visual side, then a concise explanation of the lab’s focus and activities.',
        'what_card_1_title' => 'Student engagement',
        'what_card_1_description' => 'Support student participation through mentoring, competitions, and a structured talent-development pipeline.',
        'what_card_2_title' => 'Research and funding',
        'what_card_2_description' => 'Provide compute support, proposal assistance, and funding pathways so research can move forward with stronger momentum.',
        'what_card_3_title' => 'Community and events',
        'what_card_3_description' => 'Connect the lab with broader communities through workshops, bootcamps, public discussions, and collaborative events.',
        'resources_title' => 'Resources and services',
        'resources_description' => 'This set is arranged so it can later expand into linked pages, downloads, or dedicated detail pages without changing the structure.',
        'resource_open_learning_title' => 'Opening learning',
        'resource_open_learning_description' => 'A place for open learning materials, video links, and public learning content.',
        'resource_open_learning_link' => 'Open resource',
        'resource_open_learning_url' => '',
        'resource_module_title' => 'Module',
        'resource_module_description' => 'Learning modules that can support classes, workshops, and guided sessions.',
        'resource_dataset_title' => 'Dataset',
        'resource_dataset_description' => 'Curated datasets relevant to research, teaching, and analytical prototypes.',
        'resource_workshops_title' => 'Workshop',
        'resource_workshops_description' => 'Regular training sessions for students, lecturers, and industry or government partners.',
        'resource_intern_title' => 'Intern opportunity',
        'resource_intern_description' => 'Research internship opportunities for students who want hands-on involvement with the lab.',
        'resource_cosmos_title' => 'COSMOS',
        'resource_cosmos_description' => 'Collaborative open systems for modeling and experimentation in social simulation.',
        'events_title' => 'Events',
        'events_description' => 'Use this section as a simple event grid or an upcoming activity showcase.',
        'event_1_title' => 'Workshop',
        'event_1_description' => 'Focused training sessions for practical research skills and lab tools.',
        'event_2_title' => 'Bootcamp',
        'event_2_description' => 'An intensive program covering data, coding, and modeling essentials.',
        'event_3_title' => 'PBL',
        'event_3_description' => 'Project Based Learning activities that strengthen student research habits.',
        'event_4_title' => 'Data Detective',
        'event_4_description' => 'Case-based data analysis activities and problem-solving challenges.',
        'event_5_title' => 'ECL',
        'event_5_description' => 'Academic events that encourage collaboration across communities and disciplines.',
        'event_6_title' => 'STEP K-12',
        'event_6_description' => 'Outreach activities for K-12 learners and early data-literacy engagement.',
        'people_title' => 'Core team structure',
        'people_description' => 'Use these cards to present names, roles, and short focus summaries for each team member.',
        'people_1_name' => 'Team member name',
        'people_1_bio' => 'Fill in the photo, title, and short bio to match your site needs.',
        'people_2_name' => 'Team member name',
        'people_2_bio' => 'Fill in the photo, title, and short bio to match your site needs.',
        'people_3_name' => 'Team member name',
        'people_3_bio' => 'Fill in the photo, title, and short bio to match your site needs.',
        'people_4_name' => 'Team member name',
        'people_4_bio' => 'Fill in the photo, title, and short bio to match your site needs.',
        'people_5_name' => 'Team member name',
        'people_5_bio' => 'Fill in the photo, title, and short bio to match your site needs.',
        'people_6_name' => 'Team member name',
        'people_6_bio' => 'Fill in the photo, title, and short bio to match your site needs.',
        'people_7_name' => 'Team member name',
        'people_7_bio' => 'Fill in the photo, title, and short bio to match your site needs.',
        'connect_title' => 'Contact information',
        'connect_description' => 'Keep all primary communication channels here so visitors can reach the lab quickly.',
        'contact_email' => 'bigdatalab@sbm.itb.ac.id',
        'contact_website' => 'ssbdba.itb.ac.id',
        'contact_website_url' => 'https://ssbdba.itb.ac.id',
        'contact_address' => 'SSDATALAB, Labtek XIX, 3rd Floor, Jl. Ganesha Nol 10, Bandung 40132',
        'contact_phone' => '+62 22 7566456',
        'contact_linkedin' => '',
        'contact_instagram' => '',
        'contact_tiktok' => '',
        'contact_facebook' => '',
        'contact_youtube' => '',
    ],
    'locale_overrides' => [
        'id' => [
            'hero_title' => 'Laboratorium Social Simulation and Big Data Analytics',
            'hero_description' => 'Laboratorium riset yang berfokus pada simulasi sosial, analitik big data, dan pendekatan kolaboratif untuk mendukung pembelajaran, penelitian, dan pengabdian akademik.',
            'who_description' => 'Laboratorium riset yang berfokus pada simulasi sosial, analitik big data, dan pendekatan kolaboratif untuk mendukung pembelajaran, penelitian, dan pengabdian akademik.',
            'who_establish' => 'Membangun ekosistem riset yang terstruktur, terbuka, dan berlandaskan akademik.',
            'who_value' => 'Menciptakan nilai melalui riset, pengembangan talenta, dan kolaborasi lintas disiplin.',
            'who_overview' => 'Mendorong dampak nyata melalui pendekatan berbasis data dan pemodelan sosial.',
            'brand_guidelines_description' => 'Gunakan logo secara konsisten, hindari duplikasi nama lab pada header, dan pertahankan deskripsi Social Simulation & Big Data Analytics sebagai penjelas brand.',
            'what_intro_title' => 'Program riset dan aktivitas yang ditata jelas dan mudah dipahami',
            'what_intro_description' => 'Struktur ini menjaga tampilan tetap tegas dan mudah dipindai: sisi visual yang kuat, lalu penjelasan fokus aktivitas lab secara ringkas.',
            'what_card_1_title' => 'Keterlibatan mahasiswa',
            'what_card_1_description' => 'Mendorong partisipasi mahasiswa melalui mentoring, kompetisi, dan jalur pengembangan talenta yang terstruktur.',
            'what_card_2_title' => 'Riset dan pendanaan',
            'what_card_2_description' => 'Menyediakan dukungan komputasi, pendampingan proposal, dan akses pendanaan agar riset berjalan lebih konsisten.',
            'what_card_3_title' => 'Komunitas dan acara',
            'what_card_3_description' => 'Menghubungkan lab dengan komunitas lewat workshop, bootcamp, diskusi publik, dan kegiatan kolaboratif.',
            'resources_title' => 'Sumber daya dan layanan',
            'resources_description' => 'Daftar ini disusun agar mudah dikembangkan menjadi halaman detail, unduhan, atau tautan resmi di tahap berikutnya.',
            'resource_open_learning_title' => 'Opening learning',
            'resource_open_learning_description' => 'Ruang untuk materi pembelajaran terbuka, video, dan konten belajar publik.',
            'resource_open_learning_link' => 'Buka sumber',
            'resource_module_title' => 'Modul',
            'resource_module_description' => 'Modul pembelajaran untuk kelas, workshop, dan sesi pendampingan.',
            'resource_dataset_title' => 'Dataset',
            'resource_dataset_description' => 'Kumpulan dataset relevan untuk kebutuhan riset, pembelajaran, dan prototipe analitik.',
            'resource_workshops_title' => 'Workshop',
            'resource_workshops_description' => 'Pelatihan berkala untuk mahasiswa, dosen, dan mitra industri atau pemerintahan.',
            'resource_intern_title' => 'Kesempatan magang',
            'resource_intern_description' => 'Peluang magang riset bagi mahasiswa yang ingin terlibat langsung dalam kegiatan lab.',
            'resource_cosmos_title' => 'COSMOS',
            'resource_cosmos_description' => 'Collaborative open systems for modeling untuk eksperimen dan simulasi kolaboratif.',
            'events_title' => 'Agenda kegiatan',
            'events_description' => 'Bagian ini menampilkan daftar kegiatan utama laboratorium dalam format kartu.',
            'event_1_title' => 'Workshop',
            'event_1_description' => 'Pelatihan terfokus untuk keterampilan riset praktis dan penggunaan tools lab.',
            'event_2_title' => 'Bootcamp',
            'event_2_description' => 'Program intensif untuk fondasi data, coding, dan pemodelan.',
            'event_3_title' => 'PBL',
            'event_3_description' => 'Kegiatan Project Based Learning untuk memperkuat kebiasaan riset mahasiswa.',
            'event_4_title' => 'Data Detective',
            'event_4_description' => 'Aktivitas analisis data berbasis studi kasus dan tantangan pemecahan masalah.',
            'event_5_title' => 'ECL',
            'event_5_description' => 'Kegiatan akademik untuk mendorong kolaborasi lintas komunitas dan disiplin.',
            'event_6_title' => 'STEP K-12',
            'event_6_description' => 'Kegiatan penguatan literasi data untuk pelajar tingkat K-12.',
            'people_title' => 'Struktur tim inti',
            'people_description' => 'Gunakan kartu ini untuk menampilkan nama, peran, dan fokus singkat tiap anggota tim.',
            'connect_title' => 'Informasi kontak',
            'connect_description' => 'Simpan kanal komunikasi utama di sini agar pengunjung dapat terhubung ke lab dengan cepat.',
            'contact_website' => 'Website SSBDBA',
            'contact_address' => 'SSDATALAB, Labtek XIX, 3rd Floor, Jl. Ganesha Nol 10, Bandung 40132',
        ],
    ],
    'sections' => [
        [
            'title' => 'Who we are',
            'fields' => [
                ['key' => 'hero_title', 'label' => 'Hero title', 'type' => 'text'],
                ['key' => 'hero_description', 'label' => 'Hero description', 'type' => 'textarea'],
                ['key' => 'who_description', 'label' => 'Who we are description', 'type' => 'textarea'],
                ['key' => 'who_establish', 'label' => 'Establish', 'type' => 'textarea'],
                ['key' => 'who_value', 'label' => 'Value', 'type' => 'textarea'],
                ['key' => 'who_overview', 'label' => 'Overview', 'type' => 'textarea'],
                ['key' => 'brand_guidelines_description', 'label' => 'Brand guidelines', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'What we do',
            'fields' => [
                ['key' => 'what_intro_title', 'label' => 'Intro title', 'type' => 'text'],
                ['key' => 'what_intro_description', 'label' => 'Intro description', 'type' => 'textarea'],
                ['key' => 'what_card_1_title', 'label' => 'Card 1 title', 'type' => 'text'],
                ['key' => 'what_card_1_description', 'label' => 'Card 1 description', 'type' => 'textarea'],
                ['key' => 'what_card_2_title', 'label' => 'Card 2 title', 'type' => 'text'],
                ['key' => 'what_card_2_description', 'label' => 'Card 2 description', 'type' => 'textarea'],
                ['key' => 'what_card_3_title', 'label' => 'Card 3 title', 'type' => 'text'],
                ['key' => 'what_card_3_description', 'label' => 'Card 3 description', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'Resources and Services',
            'fields' => [
                ['key' => 'resources_title', 'label' => 'Section title', 'type' => 'text'],
                ['key' => 'resources_description', 'label' => 'Section description', 'type' => 'textarea'],
                ['key' => 'resource_open_learning_title', 'label' => 'Open learning title', 'type' => 'text'],
                ['key' => 'resource_open_learning_description', 'label' => 'Open learning description', 'type' => 'textarea'],
                ['key' => 'resource_open_learning_link', 'label' => 'Open learning link label', 'type' => 'text'],
                ['key' => 'resource_open_learning_url', 'label' => 'Open learning link URL', 'type' => 'text'],
                ['key' => 'resource_module_title', 'label' => 'Module title', 'type' => 'text'],
                ['key' => 'resource_module_description', 'label' => 'Module description', 'type' => 'textarea'],
                ['key' => 'resource_dataset_title', 'label' => 'Dataset title', 'type' => 'text'],
                ['key' => 'resource_dataset_description', 'label' => 'Dataset description', 'type' => 'textarea'],
                ['key' => 'resource_workshops_title', 'label' => 'Workshop title', 'type' => 'text'],
                ['key' => 'resource_workshops_description', 'label' => 'Workshop description', 'type' => 'textarea'],
                ['key' => 'resource_intern_title', 'label' => 'Intern opportunity title', 'type' => 'text'],
                ['key' => 'resource_intern_description', 'label' => 'Intern opportunity description', 'type' => 'textarea'],
                ['key' => 'resource_cosmos_title', 'label' => 'COSMOS title', 'type' => 'text'],
                ['key' => 'resource_cosmos_description', 'label' => 'COSMOS description', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'Events',
            'fields' => [
                ['key' => 'events_title', 'label' => 'Section title', 'type' => 'text'],
                ['key' => 'events_description', 'label' => 'Section description', 'type' => 'textarea'],
                ['key' => 'event_1_title', 'label' => 'Event 1 title', 'type' => 'text'],
                ['key' => 'event_1_description', 'label' => 'Event 1 description', 'type' => 'textarea'],
                ['key' => 'event_2_title', 'label' => 'Event 2 title', 'type' => 'text'],
                ['key' => 'event_2_description', 'label' => 'Event 2 description', 'type' => 'textarea'],
                ['key' => 'event_3_title', 'label' => 'Event 3 title', 'type' => 'text'],
                ['key' => 'event_3_description', 'label' => 'Event 3 description', 'type' => 'textarea'],
                ['key' => 'event_4_title', 'label' => 'Event 4 title', 'type' => 'text'],
                ['key' => 'event_4_description', 'label' => 'Event 4 description', 'type' => 'textarea'],
                ['key' => 'event_5_title', 'label' => 'Event 5 title', 'type' => 'text'],
                ['key' => 'event_5_description', 'label' => 'Event 5 description', 'type' => 'textarea'],
                ['key' => 'event_6_title', 'label' => 'Event 6 title', 'type' => 'text'],
                ['key' => 'event_6_description', 'label' => 'Event 6 description', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'People',
            'fields' => [
                ['key' => 'people_title', 'label' => 'Section title', 'type' => 'text'],
                ['key' => 'people_description', 'label' => 'Section description', 'type' => 'textarea'],
                ['key' => 'people_1_name', 'label' => 'Role 1 name', 'type' => 'text'],
                ['key' => 'people_1_bio', 'label' => 'Role 1 bio', 'type' => 'textarea'],
                ['key' => 'people_2_name', 'label' => 'Role 2 name', 'type' => 'text'],
                ['key' => 'people_2_bio', 'label' => 'Role 2 bio', 'type' => 'textarea'],
                ['key' => 'people_3_name', 'label' => 'Role 3 name', 'type' => 'text'],
                ['key' => 'people_3_bio', 'label' => 'Role 3 bio', 'type' => 'textarea'],
                ['key' => 'people_4_name', 'label' => 'Role 4 name', 'type' => 'text'],
                ['key' => 'people_4_bio', 'label' => 'Role 4 bio', 'type' => 'textarea'],
                ['key' => 'people_5_name', 'label' => 'Role 5 name', 'type' => 'text'],
                ['key' => 'people_5_bio', 'label' => 'Role 5 bio', 'type' => 'textarea'],
                ['key' => 'people_6_name', 'label' => 'Role 6 name', 'type' => 'text'],
                ['key' => 'people_6_bio', 'label' => 'Role 6 bio', 'type' => 'textarea'],
                ['key' => 'people_7_name', 'label' => 'Role 7 name', 'type' => 'text'],
                ['key' => 'people_7_bio', 'label' => 'Role 7 bio', 'type' => 'textarea'],
            ],
        ],
        [
            'title' => 'Connect',
            'fields' => [
                ['key' => 'connect_title', 'label' => 'Section title', 'type' => 'text'],
                ['key' => 'connect_description', 'label' => 'Section description', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'type' => 'text'],
                ['key' => 'contact_website', 'label' => 'Website label', 'type' => 'text'],
                ['key' => 'contact_website_url', 'label' => 'Website URL', 'type' => 'text'],
                ['key' => 'contact_address', 'label' => 'Address', 'type' => 'textarea'],
                ['key' => 'contact_linkedin', 'label' => 'LinkedIn', 'type' => 'text'],
                ['key' => 'contact_instagram', 'label' => 'Instagram', 'type' => 'text'],
                ['key' => 'contact_tiktok', 'label' => 'TikTok', 'type' => 'text'],
                ['key' => 'contact_facebook', 'label' => 'Facebook', 'type' => 'text'],
                ['key' => 'contact_youtube', 'label' => 'YouTube', 'type' => 'text'],
                ['key' => 'contact_phone', 'label' => 'Phone', 'type' => 'text'],
            ],
        ],
    ],
];